services:
  - type: web
    name: forestfireanalyze
    env: python
    rootDir: FROEST-FIRE-DETECTION-main/forest-fire-detection
    buildCommand: "pip install -r requirements.txt && pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_SECRET_KEY
        generateValue: true
